# Generated by Django 4.2.7 on 2023-12-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_addr_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addr',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='详细地址'),
        ),
        migrations.AlterField(
            model_name='addr',
            name='country',
            field=models.CharField(default='', max_length=20, verbose_name='区县'),
        ),
    ]
