# Generated by Django 4.2.7 on 2024-01-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_addr_address_alter_addr_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addr',
            name='address',
            field=models.CharField(max_length=200, verbose_name='详细地址'),
        ),
        migrations.AlterField(
            model_name='addr',
            name='country',
            field=models.CharField(max_length=20, verbose_name='区县'),
        ),
    ]
