# Generated by Django 4.2.7 on 2024-01-28 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_addr_address_alter_addr_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addr',
            options={'verbose_name': '收获地址表', 'verbose_name_plural': '收获地址表'},
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': '地区表', 'verbose_name_plural': '地区表'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
        migrations.AlterModelOptions(
            name='verifcode',
            options={'verbose_name': '验证码表', 'verbose_name_plural': '验证码表'},
        ),
    ]
