# Generated by Django 4.2.7 on 2024-01-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_detail_options_alter_detail_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsgroup',
            options={'verbose_name': '商品分类表', 'verbose_name_plural': '商品分类表'},
        ),
        migrations.AddField(
            model_name='goods',
            name='desc',
            field=models.CharField(blank=True, help_text='商品描述', max_length=200, null=True, verbose_name='商品描述'),
        ),
        migrations.AlterField(
            model_name='goodsgroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片'),
        ),
    ]
